src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    //  Si le le mets dans les annontations, ca ne marche pas @Assert\Date(message="La date d'arrive n'est pas dans le bon format !")
    /**
     * @ORM\Column(type="datetime")
     * @Assert\GreaterThan("today", message="La date d'arrive au logement doit être superièure à celle d'aujourd'hui", groups={"front"})
     */
    private $arriveDate;

    // Si le le mets dans les annontations, ca ne marche pas @Assert\Date(message="La date d'arrive n'est pas dans le bon format !")
    /**
     * @ORM\Column(type="datetime")
     * @Assert\GreaterThan(propertyPath="arriveDate", message="La date de départ doit être superièure à celle d'arrivée")
     * 
     */
    private $leaveDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $totalPrice;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @ORM\Column(type="integer")
     * @Assert\GreaterThan(value = 0, message="Le nombre de voyageurs doit être superieur à 0")
     * 
     */
    private $travelers;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getArriveDate(): ?\DateTimeInterface
    {
        return $this->arriveDate;
    }

    public function setArriveDate(\DateTimeInterface $arriveDate): self
    {
        $this->arriveDate = $arriveDate;

        return $this;
    }

    public function getLeaveDate(): ?\DateTimeInterface
    {
        return $this->leaveDate;
    }

    public function setLeaveDate(\DateTimeInterface $leaveDate): self
    {
        $this->leaveDate = $leaveDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getTotalPrice(): ?float
    {
        return $this->totalPrice;
    }

    public function setTotalPrice(float $totalPrice): self
    {
        $this->totalPrice = $totalPrice;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getTravelers(): ?int
    {
        return $this->travelers;
    }

    public function setTravelers(int $travelers): self
    {
        $this->travelers = $travelers;

        return $this;
    }

    /**
     * On enregistre la date de création de la réservation et le montantTotal
     *  @ORM\PrePersist
     *  @ORM\PreUpdate
     * 
     * @return void
     */
    public function prePersist(){
        // Si le champ date de création est vide, on lui donne la date au moment de la réservation
        if(empty($this->createdAt)) {
            $this->createdAt = new \DateTime();
        }

        // On calcule le montant total du séjour
        if(empty($this->totalPrice)) {
            $this->totalPrice = $this->ad->getPrice() * $this->getTotalDays();
        }
    }

    // On calcule le nombre de jours totals de la reservation, on calcule la difference entre la date de sortie et d'entrée
    public function getTotalDays() {
        $total_days = $this->leaveDate->diff($this->arriveDate);

        return $total_days->days;
    }

    /**
     * Permet de verifier si les dates choisies par l'utilisateur sont disponibles
     *
     * @return boolean
     */ 
    public function isBookedDates() {
        // 1) Il faut connaitre les dates qui ne sont pas disponibles pour l'annonce
        $notAvailableDays = $this->ad->getNotAvailableDays();

        // 2) On compare les dates choisies avec les dates non disponibles
        $bookingDays = $this->getBookingDays();

        $formatDay = function($day){
            return $day->format('Y-m-d');
        };

        // Tableau des chaines de caractères des jours reservés
        $days = array_map($formatDay, $bookingDays);

        $notAvailable = array_map($formatDay, $notAvailableDays);
        
        // On compare les deux tableaux, s'il y a une correspondance, les dates ne sont pas disponibles, s'il ne trouve de correspondance, les dates sont disponible
        foreach($days as $day) {
            if(array_search($day, $notAvailable) !== false) {
                return false;
            }
        }
        return true;
    }

    /**
     * Permet de récupérer un tableau avec les jours qui correspondent à la reservation
     *
     * Retourne un tableau d'objets DateTime representant les jours pas disponibles
     * @return array
     */
    public function getBookingDays() {
        $resultat = range(
            $this->arriveDate->getTimestamp(),
            $this->leaveDate->getTimestamp(),
            24 * 60 * 60
        );

        $days = array_map(function($dayTimestamp){
            return new \DateTime(date('Y-m-d', $dayTimestamp));
        }, $resultat);

        return $days;
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use App\Form\ApplicationType;
use App\Form\DataTransformer\FrenchToDateTimeTransform;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class BookingType extends ApplicationType
{

    private $transformer;
    public function __construct(FrenchToDateTimeTransform $transformer) {
        $this->transformer = $transformer;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('arriveDate', TextType::class, $this->getConfiguration("Date d'arrivée", "Date à laquelle vous arrivez"))
            ->add('leaveDate', TextType::class, $this->getConfiguration("Date de sortie", "Date à laquelle vous quitez la location"))
            ->add('travelers', IntegerType::class, $this->getConfiguration("Voyageurs", "Nombre de voygeurs"))
            ->add('comment', TextareaType::class, $this->getConfiguration(false, "Laissez un commentaire au proprietaire si vous en avez besoin.", ["required" => false]))
        ;

        $builder->get('arriveDate')->addModelTransformer($this->transformer);
        $builder->get('leaveDate')->addModelTransformer($this->transformer);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
            'validation_groups' => ['Default', 'front']
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Comment;
use App\Entity\Booking;
use App\Form\CommentType;
use App\Form\BookingType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BookingController extends AbstractController
{
    /**
     * @Route("/ad/{slug}/book", name="booking_create")
     * @IsGranted("ROLE_USER")
     * 
     * @param MailerInterface $mailer
     * @param Ad $ad
     * @param Request $request
     * @param EntityManagerInterface $manager
     * 
     * @return Response
     * 
     */
    public function book(MailerInterface $mailer, Ad $ad, Request $request, EntityManagerInterface $manager)
    {
        $booking = new Booking();

        $form = $this->createForm(BookingType::class, $booking);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();

            $booking->setBooker($user)
                        ->setAd($ad);

            // Si les dates ne sont pas disponibles on affiche un message d'erreur
            if(!$booking->isBookedDates()) {
                $this->addFlash(
                    'danger',
                    'Les dates que vous avez choisie ne sont pas disponibles, changez de dates svp.'
                );
            } else {

                $manager->persist($booking);
                $manager->flush();
                
                $email = new TemplatedEmail();

                $email->from('javiTestMail@example.com')
                      ->to($user->getEmail())
                      ->subject("Reservation n° {$booking->getId()}")
                      ->htmlTemplate("email/bookingConfirm.html.twig")
                      ->context([
                          'booking' => $booking,
                          'ad' => $booking->getAd(),
                          'user' =>$user
                      ]);
                
                $mailer->send($email);
                
                return $this->redirectToRoute('booking_show', ['id' => $booking->getId(), 'whithAlert' => true]);
            }

        }
        
        return $this->render('booking/book.html.twig', [
            'ad' => $ad,
            'form' => $form->createView()
        ]);
    }

    /**
     * Permet d'afficher le detail d'une reservation
     *
     * @Route("booking/{id}", name="booking_show")
     * 
     * @param Booking $booking
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @return Response
     */
    public function show(Request $request, Booking $booking, EntityManagerInterface $manager) {

        $comment = new Comment();

        $form = $this->createForm(CommentType::class, $comment);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {

            $comment->setAd($booking->getAd())
                        ->setAuthor($this->getUser());
            
            $manager->persist($comment);

            $manager->flush();

            $this->addFlash(
                'success',
                'Votre commentaire a bien été pris en compte !'
            );
        }

        return $this->render('booking/show.html.twig', [
            'booking' => $booking,
            'form' => $form->createView()
        ]);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation de l'annonce {{ ad.title }}{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
{% endblock %}

{% block body %}
    <div class="container booking-book mt-5">
        <h1>Reserver : {{ ad.title }}</h1>
        <h5 class="mt-4">Cette anonce est proposé par <strong>{{ ad.author.nickName }}</strong></h5>
        {{ form_start(form) }}
        <div class="alert alert-dark mt-4">
            <h2>Choisisez les dates de votre séjour</h2>
            <div class="row mt-3">
                <div class="col-sm-12 col-md-6">
                    {{ form_row(form.arriveDate) }}
                </div>
                <div class="col-sm-12 col-md-6">
                    {{ form_row(form.leaveDate) }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <small class="d-none ad-capacity">{{ ad.capacity }}</small>
                    {{ form_row(form.travelers) }}
                </div>
            </div>
        </div>
        <div class="row mt-5 price-recap">
            <div class="col-sm-12 col-md-6 duration">
                <h4>
                    <strong>
                        <span id="days">...</span>
                    </strong> 
                    nuit(s) à {{ ad.price}}&euro; / nuit
                </h4>
            </div>
            <div class="col-sm-12 col-md-6 total-price">
                <h4>
                    Montant du séjour : 
                    <span id="totalPrice">...</span> 
                    &euro;
                </h4>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-12 ">
                <h5>Ecrire à l'hôte {{ ad.author.fullName }}</h5>
                {{ form_row(form.comment) }}
            
                <button type="submit" class="btn btn-success mt-3 w-25">Reserver</button>
                
                {{ form_end(form) }}

            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.js"></script>
    <script>
        $(document).ready(function(){
            $('#booking_arriveDate, #booking_leaveDate').datepicker({
                 format: 'dd/mm/yyyy',
                 datesDisabled: [
                     {% for day in ad.notAvailableDays %}
                        "{{ day.format('d/m/Y') }}",
                     {% endfor %}
                 ],
                 startDate: new Date()
            });

            let capacity = $('.ad-capacity')[0].innerText;
            $('#booking_travelers').attr("min", 1);
            $('#booking_travelers').attr("max", capacity);

            $('#booking_arriveDate, #booking_leaveDate').on('change', calculateAmount);

            function calculateAmount() {
                // On récupére les dates
                // Avec le regex on récupére 18/02/2020 et on le transforme en 18-02-2020
                const leaveDate = new Date($('#booking_leaveDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
                const arriveDate = new Date($('#booking_arriveDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));

                if (arriveDate && leaveDate && arriveDate < leaveDate) {
                    const DAY_TIME = 24 * 60 * 60 * 1000;

                    const interval = leaveDate.getTime() - arriveDate.getTime();
                    const days = interval / DAY_TIME;
                    const totalPrice = days * {{ ad.price }};

                    $('#days').text(days);
                    $('#totalPrice').text(totalPrice.toLocaleString('fr-FR'));

                }
            }
        });
    </script>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation n° {{ booking.id }}{% endblock %}

{% block body %}

	{% include 'partials/profileNavbar.html.twig' %}

	{% set hote = booking.ad.author %}
	{% set ad = booking.ad %}

	<div class="container booking-show my-5">
		{# Si on vient de réserver l'annonce un bandeau avec un message sera affiché #}
		{% if app.request.query.get('whithAlert') %}
			<div class="alert alert-success mt-5">
				<p>La reservation de l'hebergement
					<strong>{{ ad.title}}</strong>
					proposée par
					<strong>{{ hote.fullName }}</strong>
					a bien été pris en compte, preparez vos bagages !!!</p>
			</div>
		{% endif %}
		<h1>Reservation du bien :
			{{ ad.title }}</h1>
		<div class="row my-5">
			<div class="col-sm-12 col-md-6 booking-details shadow">
				<h2>Détails de la réservation</h2>
				<ul>
					<li>
						<strong>N° de reservation :</strong>
						{{ booking.id }}</li>
					<li>
						<strong>Voyageurs :</strong>
						{{ booking.travelers }}
						personnes</li>
					<li>
						<strong>Date d'arrivée :</strong>
						{{ booking.arriveDate | date('d/m/Y') }}</li>
					<li>
						<strong>Date de sortie :</strong>
						{{ booking.leaveDate | date('d/m/Y') }}</li>
					<li>
						<strong>Nombre de nuits :</strong>
                        {{ booking.totalDays }}</li>
					<li>
						<strong>Montant total :</strong>
						{{ booking.totalPrice }}&euro;</li>
					<li>
						<strong>Message pour l'hôte :</strong>
						{{ booking.comment | default('Aucun commentaire') }}</li>
				</ul>
			</div>
			<div class="col-sm-12 col-md-6">
				<div class="user-detail-card shadow">
					<h2>Détails de l'hôte</h2>
					<img src="{{hote.avatar}}" alt="Avatar de {{ hote.fullName }}" class="avatar-medium">
					<ul>
						<li>Nom de l'hote :
							<strong>{{ hote.fullName }}</strong>
						</li>
						<li>Email:
							<strong>{{ hote.email }}</strong>
						</li>
						<li>Numéro de contacte:
							<strong>{{ hote.phone }}</strong>
						</li>
					</ul>
					<a href="{{ path("user_show", {"slug": hote.slug}) }}" class="btn btn-primary">Savoir plus sur l'hote</a>
				</div>
			</div>
		</div>
		<div class="row my-5">
			<div class="col-12 ad-rent-details">
				<h2>Détails de l'hebergement</h2>
				<img src="/images/{{ ad.coverImage }}" alt="Image de l'annonce {{ ad.title }}" class="my-4">
				<h4 class="mb-4">Titre :
					{{ ad.title }}</h4>
				<p>Description :
					{{ ad.description | raw }}</p>
				<hr class="my-5">
				<h3>Caracteristiques</h3>
				<div class="row my-5">
					<div class="col-6">
						<p>
							<i class="fas fa-map-marker-alt"></i>
							{{ ad.fullAddress }}</p>
						<p>
							<i class="fas fa-home"></i>
							{{ ad.houseType.name }}</p>
						<p>
							<i class="fas fa-door-closed"></i>
							{{ ad.rooms}}
							chambre(s)</p>
					</div>
					<div class="col-6">
						<p>
							<i class="fas fa-bed"></i>
							{{ ad.beds }}
							lit(s)</p>
						<p>
							<i class="fas fa-toilet"></i>
							<i class="fas fa-shower"></i>
							{{ ad.bathrooms }}
							Salle(s) de bain</p>
						<p>
							<i class="fas fa-moon"></i>
							Prix :
							{{ ad.price }}€ / nuit</p>
					</div>
				</div>
				<hr class="my-5">
				<div class="row">
					<div class="col-12">
						<p>
							<strong>Equipements :
							</strong>
							{% for equipment in ad.equipments %}
								{{ equipment.name }},
							{% endfor %}
						</p>
					</div>
				</div>
				<div class="row">
					<div class="col-12">
						<p>
							<strong>Thematique(s) :
							</strong>
							{% for theme in ad.themes %}
								{{ theme.name }},
							{% endfor %}
						</p>
						<p></p>
					</div>
				</div>

				<a href="{{ path("ad_show", {"slug": ad.slug}) }}" class="btn btn-primary mt-5">Savoir plus sur l'annonce</a>
			</div>
		</div>
		<div class="row">
			<div
				class="col-12">

				{# Si la date actuelle est superieure à la date de sortie on afffiche le formulaire #}
				{% if date() > date(booking.leaveDate) %}

					{% set comment = booking.ad.commentFromAuthor(app.user) %}

					{% if comment is not null %}

						<h2>Voici votre commentaire :</h2>
						<div class="alert alert-dark px-4 py-4 shadow">
							<blockquote>{{ comment.content }}</blockquote>
							<strong>Note :
							</strong>
							{% include 'partials/notes.html.twig' with {'notes': comment.note }%}
						</div>
					{% else %}
						<h2 class="alert alert-info">Donnez votre avis, c'est important !</h2>

						{{ form_start(form) }}
						{{ form_widget(form) }}
						<button type="submit" class="btn btn-success">Confirmer</button>
						{{ form_end(form) }}

					{% endif %}
				{% else %}
					<p class="alert alert-danger">
						<strong>Vous devez attendre la fin de votre séjour pour donner votre avis !</strong>
					</p>
				{% endif %}

			</div>
		</div>
	</div>
{% endblock %}